#!/usr/bin/env python
# /// script
# dependencies = [
#   "matplotlib>=3.11.0",
# ]
# requires-python = ">=3.13.0"
# ///
"""Generate the drawings for the ELEC 3120 notes.

Two drawings are produced, and they differ in what they are for.

``bba0_bitrate_selection.svg`` is the buffer-occupancy axis of the BBA-0
bitrate rule: the bitrate to choose against how full the buffer is, with the
three regions the rule divides that axis into. The regions are what the rule
itself is made of, so the note that states the rule shows the drawing. It prints
no text, for the reason the pipe-model drawing gives: it stands on the prompt
side of a recognition card, so a label would print the answer. The alt text of
the embed, and the prose beside it, name the parts. The extent markers are drawn
as drafting arrows with extension lines rather than curly braces, which is the
notation the pipe-model drawing uses and which stays legible at the size a note
renders a figure.

``agent_execution_loop.svg`` is the agent execution loop: the model deciding
whether to call a tool or to answer, the tool call and its result going round
the loop, and the separate path out to a final answer when no tool call is
needed. This one is labelled throughout, because the loop is carried by what the
arrows are called and nothing else, and because the note cards it for recall as
well as for recognition.

Output is written beside this script so that it can be committed. Run it with
``uv run <path to this file>``. The pipe-model drawing is generated by
``generate_pipe_diagram.py`` and is not touched here.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.figure import Figure
from matplotlib.patches import Circle, FancyArrowPatch, FancyBboxPatch

# Reproducible SVG output. matplotlib salts the element ids it generates with a
# fresh uuid4 per process, so redrawing an unchanged figure still produces a
# diff; pinning the salt makes a regenerated file byte-identical to the
# committed one. The date is dropped outright via ``metadata`` below, which this
# script can do because it calls savefig on the figure itself. Changing the salt
# rewrites the SVG this script produces.
matplotlib.rcParams["svg.hashsalt"] = "information.academia-ingest"

MARK_COLOUR = "#37474f"
CURVE_COLOUR = "#8e24aa"
TEXT_COLOUR = "#37474f"
AGENT_FILL = "#d6e9d4"
EDGE_FILL = "#e6e6e6"

LOOP_SIZE = (9.2, 2.2)
BOX_CENTRE_Y = 1.20
BOX_HEIGHT = 0.46
BOX_ROUNDING = 0.08
LOOP_BOUNDARY = (2.70, 9.45, 0.44, 1.86)
RETURN_Y = 0.62
BYPASS_Y = 0.00

OCCUPANCY_TOP = 0.88
BITRATE_HIGH = 0.80
BITRATE_LOW = 0.16
LOWER_EDGE = 0.16
CUSHION_END = 0.60
FULL_EDGE = 0.94
BRACE_Y = -0.19

BBA_SIZE = (4.4, 3.4)


def _new_axes(figure: Figure):
    """Add one axis with its frame and ticks hidden."""
    axes = figure.add_subplot()
    axes.set_axis_off()
    return axes


def _double_arrow(axes, start: tuple[float, float], end: tuple[float, float]) -> None:
    """Draw a double-headed arrow between two points."""
    axes.add_patch(
        FancyArrowPatch(
            start,
            end,
            arrowstyle="<->",
            mutation_scale=11,
            color=MARK_COLOUR,
            linewidth=1.3,
            shrinkA=0,
            shrinkB=0,
        )
    )


def _span(
    axes,
    x_start: float,
    x_end: float,
    y: float,
    drop: float = 0.10,
) -> None:
    """Mark the width between two points with a double arrow and extensions."""
    _double_arrow(axes, (x_start, y), (x_end, y))
    for x in (x_start, x_end):
        axes.plot([x, x], [y + drop, y], color=MARK_COLOUR, linewidth=0.9)


def _extent_y(axes, y: float) -> None:
    """Mark a level on the vertical axis with a short horizontal tick."""
    axes.plot([-0.04, 0.04], [y, y], color=MARK_COLOUR, linewidth=1.1)


def _extent_x(axes, x: float) -> None:
    """Mark a position on the horizontal axis with a short vertical tick."""
    axes.plot([x, x], [-0.05, 0.05], color=MARK_COLOUR, linewidth=1.1)


def draw_axes_frame(axes) -> None:
    """Draw the L-shaped axis frame of the occupancy diagram."""
    axes.plot(
        [0.0, 1.06],
        [0.0, 0.0],
        color=MARK_COLOUR,
        linewidth=1.3,
    )
    axes.plot(
        [0.0, 0.0],
        [0.0, OCCUPANCY_TOP + 0.08],
        color=MARK_COLOUR,
        linewidth=1.3,
    )
    axes.add_patch(
        FancyArrowPatch(
            (1.0, 0.0),
            (1.06, 0.0),
            arrowstyle="-|>",
            mutation_scale=10,
            color=MARK_COLOUR,
            linewidth=1.3,
        )
    )
    axes.add_patch(
        FancyArrowPatch(
            (0.0, OCCUPANCY_TOP),
            (0.0, OCCUPANCY_TOP + 0.08),
            arrowstyle="-|>",
            mutation_scale=10,
            color=MARK_COLOUR,
            linewidth=1.3,
        )
    )


def draw_selection_rule(axes) -> None:
    """Draw the bitrate rule: low plateau, ramp, high plateau."""
    vertices = [
        (0.0, BITRATE_LOW),
        (LOWER_EDGE, BITRATE_LOW),
        (CUSHION_END, BITRATE_HIGH),
        (FULL_EDGE, BITRATE_HIGH),
    ]
    axes.plot(
        [x for x, _ in vertices],
        [y for _, y in vertices],
        color=CURVE_COLOUR,
        linewidth=3.0,
        solid_capstyle="round",
    )
    for x, y in vertices:
        axes.add_patch(Circle((x, y), 0.022, facecolor=CURVE_COLOUR, edgecolor="none"))


def draw_bba_extents(axes) -> None:
    """Mark the two bitrate levels, the full buffer, and the three widths."""
    _extent_y(axes, BITRATE_LOW)
    _extent_y(axes, BITRATE_HIGH)
    _extent_x(axes, FULL_EDGE)
    _span(axes, 0.0, LOWER_EDGE, BRACE_Y)
    _span(axes, LOWER_EDGE, CUSHION_END, BRACE_Y)
    _span(axes, CUSHION_END, FULL_EDGE, BRACE_Y)


def build_bba0_selection() -> Figure:
    """Return the BBA-0 bitrate-selection drawing."""
    figure = Figure(figsize=BBA_SIZE, layout="tight")
    FigureCanvasAgg(figure)
    axes = _new_axes(figure)
    axes.set_xlim(-0.08, 1.14)
    axes.set_ylim(-0.34, OCCUPANCY_TOP + 0.12)
    axes.set_aspect("auto")
    draw_axes_frame(axes)
    draw_selection_rule(axes)
    draw_bba_extents(axes)
    return figure


def _box(
    axes,
    left: float,
    right: float,
    label: str,
    facecolor: str,
) -> None:
    """Draw a labelled rounded box centred on ``BOX_CENTRE_Y``."""
    half = BOX_HEIGHT / 2
    axes.add_patch(
        FancyBboxPatch(
            (left, BOX_CENTRE_Y - half),
            right - left,
            BOX_HEIGHT,
            boxstyle=f"round,pad=0,rounding_size={BOX_ROUNDING}",
            facecolor=facecolor,
            edgecolor=MARK_COLOUR,
            linewidth=1.2,
        )
    )
    axes.text(
        (left + right) / 2,
        BOX_CENTRE_Y,
        label,
        ha="center",
        va="center",
        fontsize=9,
        color=TEXT_COLOUR,
    )


def _poly_arrow(
    axes,
    points: tuple[tuple[float, float], ...],
    label: str,
    label_at: tuple[float, float],
    label_align: str = "center",
) -> None:
    """Draw a polyline carrying an arrowhead on its final segment."""
    for index, (start, end) in enumerate(zip(points, points[1:])):
        if index == len(points) - 2:
            axes.add_patch(
                FancyArrowPatch(
                    start,
                    end,
                    arrowstyle="-|>",
                    mutation_scale=11,
                    color=MARK_COLOUR,
                    linewidth=1.1,
                    shrinkA=0,
                    shrinkB=0,
                )
            )
        else:
            axes.plot(
                [start[0], end[0]], [start[1], end[1]], color=MARK_COLOUR, linewidth=1.1
            )
    axes.text(
        label_at[0],
        label_at[1],
        label,
        ha=label_align,
        va="bottom",
        fontsize=8.5,
        color=TEXT_COLOUR,
    )


def build_agent_execution_loop() -> Figure:
    """Return the agent execution loop drawing."""
    figure = Figure(figsize=LOOP_SIZE, layout="tight")
    FigureCanvasAgg(figure)
    axes = _new_axes(figure)
    axes.set_xlim(-0.25, 12.45)
    axes.set_ylim(-0.16, 2.05)
    axes.set_aspect("auto")

    left, right, bottom, top = LOOP_BOUNDARY
    axes.add_patch(
        FancyBboxPatch(
            (left, bottom),
            right - left,
            top - bottom,
            boxstyle="round,pad=0,rounding_size=0.10",
            facecolor="none",
            edgecolor=MARK_COLOUR,
            linewidth=1.1,
            linestyle=(0, (1.6, 1.6)),
        )
    )
    axes.text(
        (left + right) / 2,
        top - 0.10,
        "agent loop",
        ha="center",
        va="top",
        fontsize=8.5,
        color=TEXT_COLOUR,
    )

    _box(axes, 0.00, 2.00, "your prompt", EDGE_FILL)
    _box(axes, 3.05, 5.30, "the model\nevaluates", AGENT_FILL)
    _box(axes, 7.20, 9.20, "tool call(s)", AGENT_FILL)
    _box(axes, 10.30, 12.30, "final answer", EDGE_FILL)

    _poly_arrow(
        axes,
        ((2.00, BOX_CENTRE_Y), (3.05, BOX_CENTRE_Y)),
        "",
        (0.0, 0.0),
    )
    _poly_arrow(
        axes,
        ((5.30, BOX_CENTRE_Y), (7.20, BOX_CENTRE_Y)),
        "tool calls",
        (6.25, BOX_CENTRE_Y + 0.08),
    )
    _poly_arrow(
        axes,
        (
            (8.20, BOX_CENTRE_Y - BOX_HEIGHT / 2),
            (8.20, RETURN_Y),
            (4.18, RETURN_Y),
            (4.18, BOX_CENTRE_Y - BOX_HEIGHT / 2),
        ),
        "tool result",
        (6.20, RETURN_Y + 0.06),
    )
    _poly_arrow(
        axes,
        (
            (3.55, BOX_CENTRE_Y - BOX_HEIGHT / 2),
            (3.55, BYPASS_Y),
            (11.30, BYPASS_Y),
            (11.30, BOX_CENTRE_Y - BOX_HEIGHT / 2),
        ),
        "no tool calls",
        (7.40, BYPASS_Y + 0.04),
    )
    return figure


FIGURES = (
    ("bba0_bitrate_selection.svg", build_bba0_selection),
    ("agent_execution_loop.svg", build_agent_execution_loop),
)


def main(argv: list[str] | None = None) -> None:
    """Write every drawing in this set beside the script."""
    del argv
    for name, build in FIGURES:
        output = Path(__file__).with_name(name)
        build().savefig(output, format="svg", transparent=True, metadata={"Date": None})
        print(output)


def __main__() -> None:
    """Run the generator."""
    main()


if __name__ == "__main__":
    __main__()
