"""
This type stub file was generated by pyright.
"""

from country_converter.country_converter import (
    CountryConverter,
    agg_conc,
    cli_output,
    convert,
    main,
    match,
)
from country_converter.version import __version__

"""Country converter coco.

Standard abbreviation for that module: coco
"""
__author__: str
__all__ = [
    "CountryConverter",
    "__version__",
    "agg_conc",
    "cli_output",
    "convert",
    "main",
    "match",
]
